### PR TITLE
fixed BTableLite cell slot when empty or conditioned

### LINKED ISSUE #1674: BTable cell slots show default value when slot is empty
### Describe the bug

If a cell slot content is conditioned BTable prints the default  content when false. Like in the old BV2 I expect and empty slot instead

### Reproduction

https://stackblitz.com/edit/github-ui6o72?file=src%2FApp.vue

### Used Package Manager

npm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by makroxyz**
fixes #1674

### CODE REVIEW

File: packages/bootstrap-vue-next/src/components/BTable/BTableLite.vue [hunk 1]
```diff
@@ -103,7 +103,9 @@
                 "
                 :details-showing="item._showDetails ?? false"
               >
-                {{ formatItem(item, field.key, field.formatter) }}
+                <template v-if="!$slots[`cell(${field.key})`] && !$slots['cell()']">
```
Comment (VividLemon) [inline packages/bootstrap-vue-next/src/components/BTable/BTableLite.vue:106]: I don't quite understand the effect. The code here should be made the default, which will only appear when the slot isn't used.

Comment (makroxyz) [reply packages/bootstrap-vue-next/src/components/BTable/BTableLite.vue:106]: have a look here

**Comment by VividLemon** [comment]
I had forgotten to ask before I merged this, but do the other fields work similarly? Such as 
https://github.com/bootstrap-vue-next/bootstrap-vue-next/pull/1675/files#diff-798f265faf0ec8e8d395983b2a3e9eb972f91083f5f91852178ead74b95e4c93R161
